#!/bin/sh
mount -t devtmpfs devtmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys
echo "=== interactive init: starting shell ==="
while true; do
	/bin/sh
	echo "[shell exited, respawning]"
done
